### ISSUE TITLE
W? - Backend Minesweeper Class

### ISSUE THREAD

**Issue by iskapoor** [jlaaa/group-l#67]

**Comment by algolg** [comment]
https://github.com/jlaaa/group-l/commit/bd46c962fecebefa5a4ddeefd5436275867cec02
Ishan created a class that creates a MineSweeper board. 0-10 function as one would expect while -1 represent mines.

https://user-images.githubusercontent.com/55261146/155940859-3b039edc-af7f-4b43-b334-96bc89c61ca7.mp4
