### ISSUE TITLE
W? - Minesweeper Class Variable Length, Width, Difficulty, and Class format

### ISSUE THREAD

**Issue by iskapoor** [jlaaa/group-l#68]

**Comment by algolg** [comment]
https://github.com/jlaaa/group-l/commit/d774cac782ddbc031daec2509ee0e486fa0d9693
After we changed class methods from static mode to instance mode, we created variables that alter width and difficulty
Lower difficulty means fewer mines, higher difficulty means more mines.

https://user-images.githubusercontent.com/55261146/155941299-fd039491-1362-4236-80c5-53424be746f2.mp4

.
