### ISSUE TITLE
W? - Akhil Minesweeper MVC integration with Ishan Minesweeper Backend

### ISSUE THREAD

**Issue by iskapoor** [jlaaa/group-l#69]

**Comment by algolg** [comment]
https://github.com/jlaaa/group-l/commit/d8d8d8761af5ece5784261a9ef0bd78734dbcb36
Frontend display for minesweeper class created

![image](https://user-images.githubusercontent.com/55261146/155941634-3b346ed5-3992-46bb-9dce-3236027d64bb.png)
