### ISSUE TITLE
W? - Akman's Minesweeper Interface

### ISSUE THREAD

**Issue by iskapoor** [jlaaa/group-l#70]

**Comment by algolg** [comment]
Timer and restart button with difficulty settings are on the left, the main minesweeper board is on the right.

![image](https://user-images.githubusercontent.com/55261146/155948282-d8ee5105-8841-44e1-9cb3-7f1782b55fd9.png)

The board is much more colorful after finishing a game.

![image](https://user-images.githubusercontent.com/55261146/155948203-a9b530b8-ae71-4810-a464-3045842afff3.png)
