### ISSUE TITLE
W? - Frontend Grid Consistent Allignment

### ISSUE THREAD

**Issue by iskapoor** [jlaaa/group-l#73]

**Comment by algolg** [comment]
https://github.com/jlaaa/group-l/commit/3b249ff51ab32893e255385698913a7e60e89d4b
The game should work on more displays now. I tested this by zooming in to an unreasonably high level and checking to see if anything looks off. While numbers were off center, this is a significant improvement from what a minor change in zoom used to do.
After:
https://user-images.githubusercontent.com/55261146/155942939-4820350a-c107-4002-ba68-fd99ecf394a3.mp4
Before: (Courtesy to Michael for testing)
![image](https://user-images.githubusercontent.com/55261146/155943124-480d83a0-ef32-4586-8019-c803a16c8503.png)
