### ISSUE TITLE
W? - Animation upon winning (similar to MyConnect submission confetti)

### ISSUE THREAD

**Issue by iskapoor** [jlaaa/group-l#76]
it's exactly as it sounds

**Comment by algolg** [comment]
https://github.com/jlaaa/group-l/commit/bfe2bd3b85389f33e8f0be288e062f69847d412d
I used a bootstrap modal as an animation for when the player wins.

https://user-images.githubusercontent.com/55261146/155947767-d594b4bb-d929-4c50-aef9-99fa2e92acb2.mp4
